name = "aoc2024"
version = "0.1.0"
defaultTargets = ["Aoc"]

[[lean_lib]]
name = "Aoc"

[[require]]
name = "Regex"
git = "https://github.com/bergmannjg/regex"

[[lean_exe]]
name = "day11"
root = "main"
exeName = "day11"
srcDir = "day11"

[[lean_exe]]
name = "day12"
root = "main"
exeName = "day12"
srcDir = "day12"
