name = "aoc2024"
version = "0.1.0"
defaultTargets = ["Aoc"]

[[lean_lib]]
name = "Aoc"

[[require]]
name = "Regex"
git = "https://github.com/bergmannjg/regex"

[[lean_exe]]
name = "day6"
root = "Main"
